### ISSUE TITLE
Filenames not showing

### ISSUE THREAD

**Issue by Limych** [frenck/action-yamllint#19]
### Subject of the issue

The same situation as #10 but there are no filenames in a Summary too.
Please, help to solve problem: https://github.com/Limych/HomeAssistantConfiguration/actions/runs/769191693

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?

### Actual behavior

What happens instead?

**Comment by Limych** [comment]
![Screenshot from 2021-05-12 22-30-41](https://user-images.githubusercontent.com/8019701/118033978-1da61780-b372-11eb-9b81-6bd834a1833f.png)

**Comment by Limych** [comment]
Unfortunately, the problem still persists.

**Comment by Limych** [comment]
Thanks 😊

**Comment by frenck** [comment]
No problem!
